<?php
require_once __dir__ . "/Views/template/header.phtml"
?>
<script src="./lib/JS/jquery-3.2.1.min.js"></script>
<script>
    $(document).ready(function() {
        $("#messages").load('ajaxLoad.php');
        $("#userArea").submit(function() {
            $.post('ajaxPost.php', $("#userArea").serialize(), function(data){
                $('#messages').append('<div class="Brown btn-lg animated fadeInRight">' + data + '</div>');
            });
            return false;
        });
    });

</script>

<div id="messages">

</div>
<form action="POST" id="userArea" >
<label> Message</label>
    <input type="text" maxlength="255" name="messages" />
    <input type="submit" class="btn Brown" value="Post Message"/>

</form>

<?php require_once __dir__ . "/Views/template/footer.phtml"
?>
