<?php
require_once __dir__ . "/template/header.phtml";
echo __dir__;
?>
    <script src="../lib/JS/jquery-3.2.1.min.js"></script>
    <script src="../lib/JS/chat.js"></script>
    <form action="POST" id="userArea" class="col-sm-8 col-sm-offset-2">
        <div class="form-group">
            <label>Message</label>
            <input type="text" class="form-control" name="messages" id="chattxt" required/>
            <input type="submit" class="btn Brown" value="Post Message"/>
        </div>
    </form>
    <div id="messages" class="col-sm-8 col-sm-offset-2">
    </div>
<?php require_once __dir__ . "/template/footer.phtml"
?>