<?php require_once __dir__ . "/template/header.phtml";
if(isset($_SESSION['User_id']))
{
    require_once __dir__ . "/template/nav.phtml";
}
echo $view->result;
?>
<?php
if(isset($_SESSION["User_id"])) {
    echo '  
<div class="row">
    <div class="container-fluid text-center animated fadeIn" id="createLocation">
        <div class="col-lg-12 center">
            <div class="panel location" style="background-color: #50564f; font-size: 18px;">
                <div class="caption">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Create new location</button>
              
                </div>
            </div>
    </div>

    </div>
       ';
                    }else{
                        echo '<span class="right" id="LoginLink">
                    <span class="logo navbar-brand">TravelMate</span>
                        <a href="./login.php" class="btn btn-warning Brown right" > Log in</a>
                    </span>';
} ?>

</div>

<div class="modal fade black" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create new location</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="padding-bottom: 50px">
                <form role="form" name="createForm" action="<?php $_SERVER["PHP_SELF"] ?>" method="POST">
                    <div class="form-group">
                        <label for="Name" class=" control-label">Name</label>
                        <input type="text" name="Name" class="form-control half">
                    </div>
                    <div class="form-group">
                        <label for="Description" class=" control-label">Description</label>
                        <input type="text" name="Description" class="form-control half" >
                    </div>
                    <div class="right">
                    <button type="submit" name="Csubmit" class="btn btn-success btn-md">create</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">

</div>


    <div class="row">

            <div class="container-fluid" id="locations">
                <?php

                foreach($locations as $location)
                {
                    echo ' <div class="text-center animated fadeInDown" style=" color: black;margin-top: 3%;">


                               <div class="col-sm-4">
                                <div class="panel location"><p class="name blue">'. $location->getName() . '</p>' .
                                   '<div class="caption">
                                    <p>' . $location->getDescription() . '</p>
                                </div>
                                <span class="date left">'.substr((string)$location->getdate(),0,11). '</span>
                                <span class="date right">' .  substr((string)$location->getdate(),11,20)  .'</span><p> <br>';

                                    if($location->getUserId() == $_SESSION["User_id"]) {
                                     echo '<a href="./locationprofile.php?Location_id='. $location->getLocationId() .'" class="btn btn-warning btn-xs">Edit</a>';
                                    }

                                         if($location->getUserId() == $_SESSION["User_id"]) {

                                            echo '           <form action="'. $_SERVER["PHP_SELF"] .'" method = "POST" >
                                                             <input type="hidden" name="Location_id" value="'. $location->getLocationId() . '" >
                                                               <button type="submit" name="Dsubmit" class="btn btn-danger btn-xs">Delete</button>
                                                        </form > ';
                                             }
                                    echo '
                                </p> 
                            </div>
                        </div>';
                }
                ?>
                    </div>
            </div>
    </div>
<?php require_once __dir__ . "/template/footer.phtml";
?>
