<?php require_once __dir__ . "/template/header.phtml";
require_once __dir__ . "/template/nav.phtml";

?>
    <div class="well col-sm-6 col-sm-offset-3 animated pulse" id="userProfile">

        <form class="form-horizontal" role="form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="POST">


            <div class="form-group">
                <label for="Name" class=" control-label">Name</label>
                <input type="text" name="Name" value="<?php echo $Current_Location['Name'];?>" class="form-control half">
            </div>
            <div class="form-group">
                <label for="Description" class=" control-label">Description</label>
                <textarea type="text" name="Description"  class="form-control half animated flipInX"  rows="10"><?php echo $Current_Location['Description'];?>
                </textarea>
            </div>
            <input type="hidden" name="Location_id" value="<?php echo $Current_Location['Location_id'];?>" >

            <br>
            <br>
            <button type="submit" name="Usubmit" class="btn btn-info Brown center">Update</button>
            <a href="./locations.php" class="btn btn-warning Brown center">Back to Locations</a>

        </form>

        <?php echo $view->result; ?>

    </div>

<?php require_once __dir__ . "/template/footer.phtml";
?>