<?php require_once __dir__ . "/template/header.phtml";
require_once __dir__ . "/template/nav.phtml";
?>

<div class="container">



    <div class="row text-center animated bounceInUp" style="display:flex; flex-wrap: wrap;">
<!--        <% campgrounds.forEach(function(campground){ %>-->
        <div class="col-md-3 col-sm-6">
            <div class="panel">
<!--                <img class="img-thumbnail" src="../<%= campground.image %>" alt="" width="25%">-->
                <div class="caption">
<!--                    <h4><%= campground.name %></h4>-->
                </div>
                <p>
                    <a href="/campgrounds/<%= campground._id %>"class="btn btn-info btn-xs btn-more">More info</a>
                </p>
            </div>
        </div>
<!--        <% }) %>-->
    </div>
</div>
<?php require_once __dir__ . "/template/footer.phtml";
?>
