<?php require_once __dir__ . "/template/header.phtml"
?>
    <body>
      <div class="cover">
          <div class="bg">
          </div>
        </div>

      <div class="login animated fadeInDown">
        <div class="container">
            <div class="row align-middle">
                <div class="col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
                    <div class="panel panel-default" style="background-color: rgba(220, 220, 233, 0.3);">
                        <div class="panel-heading">Login</div>
                        <div class="panel-body">
                            <form class="form-horizontal" role="form" method="POST" action="">

                                <div class="form-group">
                                    <label for="email" class="col-sm-4 col-xs-4 control-label">User Name</label>

                                    <div class="col-sm-4 col-xs-8">
                                        <input id="email" class="form-control" name="Username" value="">
                                            <span class="help-block">
                                                <strong></strong>
                                            </span>

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="password" class="col-sm-4 col-xs-4 control-label">Password</label>

                                    <div class=" col-sm-4 col-xs-8">
                                        <input id="password" type="password" class="form-control" name="Password">
                                            <span class="help-block">
                                                <strong></strong>
                                            </span>

                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="col-md-6 col-md-offset-4">
                                        <button type="submit" name="Lsubmit" class="btn btn-info Brown">Login
                                        </button>
                                        <a href="register.phtml" class="btn btn-warning Brown">Sign Up!</a>
                                    </div>
                                </div>
                                <br>
                                <?php echo " $view->result"; ?>
                                <br>
                                <br>
                                <div class="col-md-6 col-md-offset">
                                        <label >
                                          In a rush?
                                            <a href="./Views/locations.phtml" class="btn btn-danger Brown"> View Locations</a>
                                        </label>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>
  </body>
<?php require_once __dir__ . "/template/footer.phtml"
?>
