<?php require_once __dir__ . "/template/header.phtml";
require_once __dir__ . "/template/nav.phtml";

?>
    <div class="well col-sm-6 col-sm-offset-3 animated pulse" id="userProfile">

        <form class="form-horizontal" role="form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="POST">


            <div class="form-group">
                <label for="email" class=" control-label">First Name</label>
                <input type="text" name="First_Name" value="<?php echo $Current_User['First_Name'];?>" class="form-control half">
            </div>
            <div class="form-group">
                <label for="email" class=" control-label">Last Name</label>
                <input type="text" name="Last_Name" value="<?php echo $Current_User['Last_Name'];?>" class="form-control half" >
            </div>
            <div class="form-group">
                <label for="email" class=" control-label">User Name</label>
                <input type="text" name="Username" value="<?php echo $Current_User['Username'];?>" class="form-control half" >
            </div>
            <div class="form-group">
                <label for="email" class=" control-label">Password</label>
                <input type="password" name="Password" value="" class="form-control half" >
            </div>
            <br>
            <br>

            <button type="submit" name="Usubmit" class="btn btn-info Brown center">Update</button>
            <a href="./Dashboard.php" class="btn btn-warning Brown center">Back to Dashboard</a>

        </form>

        <?php echo $view->result; ?>

    </div>

<?php require_once __dir__ . "/template/footer.phtml";
?>