<?php
require_once __dir__ . "/template/header.phtml";
require_once __dir__ . "/template/nav.phtml";
?>



<?php
require_once __dir__ . "/template/footer.phtml";
?>



<div class="well col-sm-6 col-sm-offset-3 animated bounceInDown" id="weather" <?php if(isset($_GET['Country']) && isset($_GET['City']) ){ echo 'style="display: none;';} ?>>

    <form class="form-horizontal" role="form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="GET">


        <div class="form-group">
            <label for="Country" class=" control-label">Country</label>
            <input type="text" name="Country" class="form-control half" placeholder="Type your desired Country ...">
        </div>
        <div class="form-group">
            <label for="City" class=" control-label">City</label>
            <input type="text" name="City" class="form-control half" placeholder="Type your desired City ...">
        </div>

        <button type="submit" name="Fsubmit" class="btn btn-info Brown center">Forcast</button>
        <a href="./Dashboard.php" class="btn btn-warning Brown center">Back to Dashboard</a>

    </form>



    <?php echo $view->result; ?>

</div>

<table class="rwd-table animated bounceInDown" <?php if(empty($_GET['Country']) && empty($_GET['City']) ){ echo 'style="display: none;';} ?>>
    <tr>
        <th>Movie Title</th>
        <th>Genre</th>
        <th>Year</th>
        <th>Gross</th>
    </tr>
    <tr>
        <td data-th="Movie Title">Star Wars</td>
        <td data-th="Genre">Adventure, Sci-fi</td>
        <td data-th="Year">1977</td>
        <td data-th="Gross">$460,935,665</td>
    </tr>
    <tr>
        <td data-th="Movie Title">Howard The Duck</td>
        <td data-th="Genre">"Comedy"</td>
        <td data-th="Year">1986</td>
        <td data-th="Gross">$16,295,774</td>
    </tr>
    <tr>
        <td data-th="Movie Title">American Graffiti</td>
        <td data-th="Genre">Comedy, Drama</td>
        <td data-th="Year">1973</td>
        <td data-th="Gross">$115,000,000</td>
    </tr>
</table>



