<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>TravelMate</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="../lib/CSS/bootstrap.min.css">
    <link rel="stylesheet" href="./lib/CSS/bootstrap.min.css">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="../lib/CSS/stylesheet.css">
    <link rel="stylesheet" href="./lib/CSS/stylesheet.css">
    <!-- Animation -->
    <link rel="stylesheet" href="../lib/CSS/animate.css">
    <link rel="stylesheet" href="./lib/CSS/animate.css">
    <a href="<?php echo __DIR__ ?>">dsadas</a>
</head>
<body>

</body>
</html>
