<?php
session_start();
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php if($view->pageTitle){echo $view->pageTitle;}else echo "TravelMate"; ?></title>
    <!-- Latest compiled and minified CSS -->


    <link rel="stylesheet" href="./lib/CSS/bootstrap.min.css">
    <!-- Custom styles for this template -->

    <link rel="stylesheet" href="./lib/CSS/stylesheet.min.css">
    <!-- Animation -->

    <link rel="stylesheet" href="./lib/CSS/animate.min.css">
</head>
<body>

</body>
</html>
