<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>TravelMate</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="/assets/css/stylesheet.css">

    <!-- Animation -->
    <link rel="stylesheet" href="/assets/css/animate.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="/assets/font-awesome/css/font-awesome.min.css">
</head>
<body>

</body>
</html>