<!-- Static navbar -->
   <nav class="navbar navbar-default" style="position: relative;z-index: 1000">
     <div class="container-fluid animated fadeIn">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="./Dashboard.php">travelMate</a>
       </div>
       <div id="navbar" class="navbar-collapse collapse">
         <ul class="nav navbar-nav">
           <li><a href="./Dashboard.php">Home</a></li>
           <li><a href="./locations.php">Locations</a></li>
           <li><a href="./Chat.php">Chat</a></li>
           <li><a href="./weatherForecast.php">Weather Forecast</a></li>

         </ul>
         <ul class="nav navbar-nav navbar-right">
           <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></a>
             <ul class="dropdown-menu">
               <li><a href="./UserProfile.php"><?php echo "profile - " . $_SESSION['First_Name'];?></a></li>
               <li role="separator" class="divider"></li>
               <li><a href="./Views/template/logout.php">Logout</a></li>
             </ul>
           </li>
         </ul>
       </div><!--/.nav-collapse -->
     </div><!--/.container-fluid -->
   </nav>
<style media="screen">


    .dropdown-menu{
      font-size: 12px !important;
  }
</style>
